table world_gdp_data
	lineageTag: 2ca2d6ca-cc4d-41bc-82ff-56b577286b8d

	measure 'Total GDP' = SUM(world_gdp_data[GDP])
		lineageTag: 0d67d3fa-3c34-49ed-918d-6419e74f1b90

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Debt-to-GDP = ([Total Debt]/[Total GDP])*100
		lineageTag: e736be49-8d90-449c-881e-1e0a8141f0a4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column country_name
		dataType: string
		lineageTag: 263e0873-0421-4a37-8c7c-3e5d6a1ff7de
		summarizeBy: none
		sourceColumn: country_name

		annotation SummarizationSetBy = Automatic

	column indicator_name
		dataType: string
		lineageTag: f5111bad-eeda-4804-92ed-3ab36bc80f61
		summarizeBy: none
		sourceColumn: indicator_name

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: string
		lineageTag: 51159633-61ff-4855-88a9-4f6b10b38105
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column GDP
		dataType: double
		lineageTag: 3f4ebfc0-f6ed-4562-b823-751799c22e01
		summarizeBy: sum
		sourceColumn: GDP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition world_gdp_data = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\tunji\Documents\BI_Class\BI_Class\world_gdp_data.csv"),[Delimiter=",", Columns=47, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type number}, {"Column4", type number}, {"Column5", type number}, {"Column6", type number}, {"Column7", type number}, {"Column8", type number}, {"Column9", type number}, {"Column10", type number}, {"Column11", type number}, {"Column12", type number}, {"Column13", type number}, {"Column14", type number}, {"Column15", type number}, {"Column16", type number}, {"Column17", type number}, {"Column18", type number}, {"Column19", type number}, {"Column20", type number}, {"Column21", type number}, {"Column22", type number}, {"Column23", type number}, {"Column24", type number}, {"Column25", type number}, {"Column26", type number}, {"Column27", type number}, {"Column28", type number}, {"Column29", type number}, {"Column30", type number}, {"Column31", type number}, {"Column32", type number}, {"Column33", type number}, {"Column34", type number}, {"Column35", type number}, {"Column36", type number}, {"Column37", type number}, {"Column38", type number}, {"Column39", type number}, {"Column40", type number}, {"Column41", type number}, {"Column42", type number}, {"Column43", type number}, {"Column44", type number}, {"Column45", type number}, {"Column46", type number}, {"Column47", type number}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"country_name", type text}, {"indicator_name", type text}, {"1980", type number}, {"1981", type number}, {"1982", type number}, {"1983", type number}, {"1984", type number}, {"1985", type number}, {"1986", type number}, {"1987", type number}, {"1988", type number}, {"1989", type number}, {"1990", type number}, {"1991", type number}, {"1992", type number}, {"1993", type number}, {"1994", type number}, {"1995", type number}, {"1996", type number}, {"1997", type number}, {"1998", type number}, {"1999", type number}, {"2000", type number}, {"2001", type number}, {"2002", type number}, {"2003", type number}, {"2004", type number}, {"2005", type number}, {"2006", type number}, {"2007", type number}, {"2008", type number}, {"2009", type number}, {"2010", type number}, {"2011", type number}, {"2012", type number}, {"2013", type number}, {"2014", type number}, {"2015", type number}, {"2016", type number}, {"2017", type number}, {"2018", type number}, {"2019", type number}, {"2020", type number}, {"2021", type number}, {"2022", type number}, {"2023", type number}, {"2024", type number}}),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Changed Type1", {"country_name", "indicator_name"}, "Attribute", "Value"),
				    #"Renamed Columns" = Table.RenameColumns(#"Unpivoted Other Columns",{{"Attribute", "Year"}, {"Value", "GDP"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

